#!/usr/bin/python3

import argparse
import os
parser = argparse.ArgumentParser()
parser.add_argument("decks", help="how many decks")
parser.add_argument("--startat", help="how many decks", default=1)
args = parser.parse_args()


for i in range(int(args.startat),int(args.decks)+int(args.startat)):
    os.system("script/deck --deck="+str(i))
    #print(i)